[package]
name = "dummy_rollup"
version = "0.1.0"
edition = "2021"

[dependencies]
celestia-rpc = "0.4.1"
celestia-types = "0.5.0"
tokio = { version = "1.40.0", features = ["full"] }
anyhow = "1.0.89"
hex = "0.4.3"
rand = "0.8.5"
ctrlc = "3.2"
