[package]
name = "dummy_rollup"
version = "0.1.0"
edition = "2021"

[lib]
name = "dummy_rollup"
path = "src/lib.rs"

[[bin]]
name = "dummy_rollup"
path = "src/main.rs"

[[bin]]
name = "dummy_rollup_frontend"
path = "src/frontend/main.rs"

[dependencies]
celestia-rpc = "0.9.0"
celestia-types = "0.10.0"
tokio = { version = "1.40.0", features = ["full"] }
anyhow = "1.0.89"
hex = "0.4.3"
rand = "0.8.5"
chrono = "0.4"
ctrlc = "3.2"
chess = "3.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Frontend dependencies
yew = { version = "0.21", features = ["csr"] }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
    "HtmlElement",
    "Window",
    "Document",
    "Element",
    "DomRect",
    "MouseEvent",
    "WebSocket",
    "MessageEvent",
    "CloseEvent",
] }
js-sys = "0.3"
gloo = "0.10"
wasm-logger = "0.2"
log = "0.4"

# WebSocket server
tokio-tungstenite = "0.20"
futures = "0.3"
async-trait = "0.1"

[dev-dependencies]
wasm-bindgen-test = "0.3"
